port: 7880
bind_addresses:
    - ""
rtc:
    tcp_port: 80
    port_range_start: 50000
    port_range_end: 60000
    enable_loopback_candidate: false
    use_external_ip: false
redis:
    address: redis-server:6379
    username: "default"
    password: "rootroot"
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null

turn:
    enabled: true
    domain: turn.ziti.example
    tls_port: 5349
    udp_port: 3478
    relay_range_start: 30000
    relay_range_end: 40000
    external_tls: false
    cert_file: "/keys/turn.crt"
    key_file: "/keys/turn.key"
keys:
    GAkDU6thrPsKgxl: tZnZDeJGubl3tHJDPNvqfrQfmEkKcduQo0l23u9HY57
logging:
  # log level, valid values: debug, info, warn, error
  level: debug
